baseURL = 'https://husin.dev/'
languageCode = 'en-us'

title = 'Wilson Husin'

enableGitInfo = true

[build]
[build.buildStats]
enable = true

[params]
  description = "Personal site maintainted by Wilson Husin. Writing about software engineering within developer productivity, platform infrastructure, and web applications with perspectives of human-computer ergonomics and software performance."

[frontmatter]
  date = [":filename", "publishdate", ":default", ":fileModTime"]

[menu]
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about/"
  weight = "001"
[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog/"
  weight = "100"
[[menu.main]]
  identifier = "mini"
  name = "mini"
  title = "Mini"
  url = "/mini/"
  weight = "101"
[[menu.main]]
  identifier = "visual"
  name = "visual"
  title = "Visual"
  url = "/visual/"
  weight = "102"
[[menu.main]]
  identifier = "hire-me"
  name = "hire-me"
  title = "Hire me"
  url = "/hire-me/"
  weight = "901"

[markup]
  [markup.highlight]
    noClasses = false

[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true
